steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/pms-repo/pms-taskflow:latest', '--no-cache', '--build-arg', 'VITE_FIREBASE_API_KEY=AIzaSyA8WTF6H0jyVtJFumtBdH_pOKfF6f8ocsE', '--build-arg', 'VITE_FIREBASE_AUTH_DOMAIN=pms-taskflow-aa254.firebaseapp.com', '--build-arg', 'VITE_FIREBASE_PROJECT_ID=pms-taskflow-aa254', '--build-arg', 'VITE_FIREBASE_APP_ID=1:1086239964586:web:239a15d2885b99d8c87fd3', '--build-arg', 'VITE_API_BASE_URL=/api', '--build-arg', 'SKIP_SHEETS_SYNC=true', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/pms-repo/pms-taskflow:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'pms-taskflow'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/pms-repo/pms-taskflow:latest'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--port=3000'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--min-instances=1'
      - '--timeout=3600'
      - '--concurrency=80'
      - '--cpu-boost'
      - '--no-cpu-throttling'
      - '--set-env-vars=GOOGLE_SERVICE_ACCOUNT_EMAIL=pms-service-account@pms-taskflow-500309.iam.gserviceaccount.com'
      - '--set-secrets=GOOGLE_PRIVATE_KEY=GOOGLE_PRIVATE_KEY:latest'
      - '--set-env-vars=FIREBASE_PROJECT_ID=pms-taskflow-aa254'
      - '--set-env-vars=GOOGLE_SPREADSHEET_ID=1zwbskE3dTGVNn8EGG6Dx45TorL08zCB9ovLvnGeoEWQ'
      - '--set-secrets=JWT_SECRET=JWT_SECRET:latest'
      - '--set-secrets=GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest'
      - '--set-secrets=GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest'
      - '--set-env-vars=JWT_EXPIRES_IN=7d'
      - '--set-env-vars=BCRYPT_ROUNDS=12'
      - '--set-env-vars=RATE_LIMIT_WINDOW_MS=900000'
      - '--set-env-vars=RATE_LIMIT_MAX_REQUESTS=1000'
      - '--set-env-vars=NODE_ENV=production'
      - '--set-env-vars=VITE_API_BASE_URL=/api'
      - '--set-env-vars=APP_URL=https://pms-taskflow-556944241861.us-central1.run.app'
      - '--set-env-vars=GMAIL_REDIRECT_URI=https://pms-taskflow-556944241861.us-central1.run.app/api/auth/gmail/callback'
      - '--set-env-vars=DEFAULT_FALLBACK_EMAIL=rajeev.1@pw.live'
      - '--set-env-vars=REMINDER_SENDER_EMAIL=rajeev.1@pw.live'
      - '--set-env-vars=VITE_FIREBASE_API_KEY=AIzaSyA8WTF6H0jyVtJFumtBdH_pOKfF6f8ocsE'
      - '--set-env-vars=VITE_FIREBASE_AUTH_DOMAIN=pms-taskflow-aa254.firebaseapp.com'
      - '--set-env-vars=VITE_FIREBASE_PROJECT_ID=pms-taskflow-aa254'
      - '--set-env-vars=VITE_FIREBASE_APP_ID=1:1086239964586:web:239a15d2885b99d8c87fd3'
      - '--set-env-vars=CLOUDINARY_CLOUD_NAME=dumxy0zvl'
      - '--set-secrets=CLOUDINARY_API_KEY=CLOUDINARY_API_KEY:latest'
      - '--set-secrets=CLOUDINARY_API_SECRET=CLOUDINARY_API_SECRET:latest'
      - '--set-secrets=GMAIL_REFRESH_TOKEN=GMAIL_REFRESH_TOKEN:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: 'CLOUD_LOGGING_ONLY'
